### ISSUE TITLE
eea.daviz 10.7 has a hard dependency on eea.relations being installed.

### ISSUE THREAD

**Issue by fredvd** [eea/eea.daviz#21]
Tested in the eeacms/kgs docker image (10.2) from https://hub.docker.com/r/eeacms/kgs

When I install eea.daviz in the docker image and try to add a new visualisation I get the traceback included below. After I also install eea.relations (which is not a dependency of eea.daviz in the setup.py or metadata.xml GS profile) a visualisation can be added. 

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 32, in _call
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
   - Warning: Macro expansion failed
   - Warning: <type 'exceptions.KeyError'>: 'macro'
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 522, in do_optTag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 867, in do_useMacro
  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/plone/buildout-cache/eggs/Products.Archetypes-1.9.11-py2.7.egg/Products/Archetypes/skins/archetypes/edit_macros.pt
   - Line 105, Column 20
   - Expression: <PythonExpr context.widget(field.getName(), mode='edit')>
   - Names:
      {'container': <PloneSite at /plone>,
       'context': <DavizVisualization at /plone/portal_factory/DavizVisualization/davizvisualization.2017-04-28.5707105435 used for /plone>,
       'default': <object object at 0x7f754576f550>,
       'here': <DavizVisualization at /plone/portal_factory/DavizVisualization/davizvisualization.2017-04-28.5707105435 used for /plone>,
       'loop': {u'field': <Products.PageTemplates.Expressions.PathIterator object at 0x7f7518e810d0>,
                u'fieldset': <Products.PageTemplates.Expressions.PathIterator object at 0x7f7518e72cd0>},
       'nothing': None,
       'options': {'args': (),
                   'state': <Products.CMFFormController.ControllerState.ControllerState object at 0x7f751ad0c3d0>},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f753a8451b0>,
       'request': <HTTPRequest, URL=http://localhost:8080/plone/portal_factory/DavizVisualization/davizvisualization.2017-04-28.5707105435/atct_edit>,
       'root': <Application at >,
       'template': <FSControllerPageTemplate at /plone/atct_edit used for /plone/portal_factory/DavizVisualization/davizvisualization.2017-04-28.5707105435>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>}
  Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
   - __traceback_info__: context.widget(field.getName(), mode='edit')
  Module PythonExpr, line 1, in <expression>
  Module Products.Archetypes.BaseObject, line 276, in widget
  Module Products.Archetypes.Renderer, line 26, in render
  Module Products.Archetypes.generator.widget, line 147, in __call__
AttributeError: Macro eeareferencebrowser does not exist for <DavizVisualization at davizvisualization.2017-04-28.5707105435>

**Comment by avoinea** [comment]
@fredvd Thanks! 

Within a normal use of KGS, you should first install `EEA Plone Buildout Profile` and then other add-ons ;) 

Still, I'll test to see if the issue reproduce when using on Plone (no KGS)

**Comment by avoinea** [comment]
It doesn't reproduce when `eea.relations` is not present ;)

**Comment by fredvd** [comment]
@avoinea Do you mean it doesn't reproduce if you install eea.daviz in a simple buildout outside of the eeacms/kgs system, or does eea.daviz inside the docker image run without throwing the error (and not installing the EEA Plone Buildout Profile before, which installs eea.relations...)

I didn't experience this traceback so far when we are running a Daviz install in our own buildout setup and I didn't have to install eea.relations there to get it working.  But we are experiencing some other issues with Daviz and that's why I wanted to test Daviz by running it from the eeacms/kgs.

**Comment by avoinea** [comment]
@fredvd The issue seems to be within `eea.relations`, if it's in eggs, seems that it want to be also installed ASAP :). If you don't add `eea.relations` within buildout eggs section, then everything would be OK. Thus the issue should be filled to [eea.relations](https://github.com/eea/eea.relations/issues) repo.

See also [eeacms/daviz](https://hub.docker.com/r/eeacms/daviz/)

**Comment by fredvd** [comment]
@avoinea Ah, thanks, that makes sense (eea.relations being the cause). Thanks for the pointe tor to eeacms/daviz, I had only found and tested with the eeacms/kgs so far.
